apiVersion: apps/v1
kind: Deployment
metadata:
  name: dredfort
  namespace: dev
  labels:
    app: dredfort
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dredfort
  template:
    metadata:
      labels:
        app: dredfort
    spec:
      containers:
      - name: dredfort
        image: dredfort/iot:v1
        ports:
        - containerPort: 8888