
apiVersion: v1
kind: Service
metadata:
  name: dredfort-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: dredfort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
